// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwmegkvdpxabzdihnlbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3bWVna3ZkcHhhYnpkaWhubGJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTczMTgsImV4cCI6MjA2MjczMzMxOH0.AFFsxpUUXqRoy3_o9snWdQXZcZbdYKXaZ-vEVXmEBIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);